// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder() {
  return window['go']['backend']['App']['AddFolder']();
}

export function AddVideoToPlaylist(arg1, arg2) {
  return window['go']['backend']['App']['AddVideoToPlaylist'](arg1, arg2);
}

export function CacheHandler() {
  return window['go']['backend']['App']['CacheHandler']();
}

export function CancelUpload(arg1) {
  return window['go']['backend']['App']['CancelUpload'](arg1);
}

export function CreatePlaylist(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreatePlaylist'](arg1, arg2, arg3);
}

export function DeleteFiles(arg1) {
  return window['go']['backend']['App']['DeleteFiles'](arg1);
}

export function DeleteGameProfile(arg1) {
  return window['go']['backend']['App']['DeleteGameProfile'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['backend']['App']['DeletePlaylist'](arg1);
}

export function DisconnectSteam() {
  return window['go']['backend']['App']['DisconnectSteam']();
}

export function GetAPILogs(arg1) {
  return window['go']['backend']['App']['GetAPILogs'](arg1);
}

export function GetAutoLaunch() {
  return window['go']['backend']['App']['GetAutoLaunch']();
}

export function GetCacheDir() {
  return window['go']['backend']['App']['GetCacheDir']();
}

export function GetChannelAnalytics() {
  return window['go']['backend']['App']['GetChannelAnalytics']();
}

export function GetChannelPlaylists(arg1) {
  return window['go']['backend']['App']['GetChannelPlaylists'](arg1);
}

export function GetChannelVideosPaginated(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['GetChannelVideosPaginated'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetFolderSettings(arg1) {
  return window['go']['backend']['App']['GetFolderSettings'](arg1);
}

export function GetOrCreatePlaylist(arg1, arg2, arg3) {
  return window['go']['backend']['App']['GetOrCreatePlaylist'](arg1, arg2, arg3);
}

export function GetPlaylistVideos(arg1) {
  return window['go']['backend']['App']['GetPlaylistVideos'](arg1);
}

export function GetQuotaUsedToday() {
  return window['go']['backend']['App']['GetQuotaUsedToday']();
}

export function GetSteamAPIKey() {
  return window['go']['backend']['App']['GetSteamAPIKey']();
}

export function GetSteamAppID(arg1) {
  return window['go']['backend']['App']['GetSteamAppID'](arg1);
}

export function GetSteamDeveloperStats(arg1) {
  return window['go']['backend']['App']['GetSteamDeveloperStats'](arg1);
}

export function GetSteamGamesByDeveloper(arg1) {
  return window['go']['backend']['App']['GetSteamGamesByDeveloper'](arg1);
}

export function GetSteamGamesByPublisher(arg1) {
  return window['go']['backend']['App']['GetSteamGamesByPublisher'](arg1);
}

export function GetSteamGamesByTag(arg1) {
  return window['go']['backend']['App']['GetSteamGamesByTag'](arg1);
}

export function GetSteamID() {
  return window['go']['backend']['App']['GetSteamID']();
}

export function GetSteamOverallStats() {
  return window['go']['backend']['App']['GetSteamOverallStats']();
}

export function GetSteamPublisherStats(arg1) {
  return window['go']['backend']['App']['GetSteamPublisherStats'](arg1);
}

export function GetSteamTagStats(arg1) {
  return window['go']['backend']['App']['GetSteamTagStats'](arg1);
}

export function GetStreamPort() {
  return window['go']['backend']['App']['GetStreamPort']();
}

export function GetSyncStatus() {
  return window['go']['backend']['App']['GetSyncStatus']();
}

export function GetThumbnail(arg1) {
  return window['go']['backend']['App']['GetThumbnail'](arg1);
}

export function GetVideoDuration(arg1) {
  return window['go']['backend']['App']['GetVideoDuration'](arg1);
}

export function GetVideoPreview(arg1) {
  return window['go']['backend']['App']['GetVideoPreview'](arg1);
}

export function GetVideos(arg1) {
  return window['go']['backend']['App']['GetVideos'](arg1);
}

export function GetVideosFromFolders(arg1) {
  return window['go']['backend']['App']['GetVideosFromFolders'](arg1);
}

export function GetWatchFolderEnabled() {
  return window['go']['backend']['App']['GetWatchFolderEnabled']();
}

export function GetYouTubeChannelInfo() {
  return window['go']['backend']['App']['GetYouTubeChannelInfo']();
}

export function ImportYouTubeJSON() {
  return window['go']['backend']['App']['ImportYouTubeJSON']();
}

export function IsSteamSyncing() {
  return window['go']['backend']['App']['IsSteamSyncing']();
}

export function IsYouTubeAuthed() {
  return window['go']['backend']['App']['IsYouTubeAuthed']();
}

export function LinkLocalToYouTube(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['LinkLocalToYouTube'](arg1, arg2, arg3, arg4);
}

export function LoadConfig() {
  return window['go']['backend']['App']['LoadConfig']();
}

export function LogFrontendEvent(arg1) {
  return window['go']['backend']['App']['LogFrontendEvent'](arg1);
}

export function LoginSteam() {
  return window['go']['backend']['App']['LoginSteam']();
}

export function OpenFolderDialog() {
  return window['go']['backend']['App']['OpenFolderDialog']();
}

export function PurgePlaylistDuplicates(arg1) {
  return window['go']['backend']['App']['PurgePlaylistDuplicates'](arg1);
}

export function RegenerateThumbnail(arg1) {
  return window['go']['backend']['App']['RegenerateThumbnail'](arg1);
}

export function RemoveFolder(arg1) {
  return window['go']['backend']['App']['RemoveFolder'](arg1);
}

export function SaveFolderSettings(arg1, arg2) {
  return window['go']['backend']['App']['SaveFolderSettings'](arg1, arg2);
}

export function SaveFolders(arg1) {
  return window['go']['backend']['App']['SaveFolders'](arg1);
}

export function SaveGameProfile(arg1, arg2) {
  return window['go']['backend']['App']['SaveGameProfile'](arg1, arg2);
}

export function SaveRecentFieldValues(arg1) {
  return window['go']['backend']['App']['SaveRecentFieldValues'](arg1);
}

export function SaveSteamAPIKey(arg1) {
  return window['go']['backend']['App']['SaveSteamAPIKey'](arg1);
}

export function SaveVideoMetadata(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10) {
  return window['go']['backend']['App']['SaveVideoMetadata'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10);
}

export function SaveYouTubeCredentials(arg1, arg2) {
  return window['go']['backend']['App']['SaveYouTubeCredentials'](arg1, arg2);
}

export function SetAutoLaunch(arg1) {
  return window['go']['backend']['App']['SetAutoLaunch'](arg1);
}

export function SetTagPlaylist(arg1, arg2) {
  return window['go']['backend']['App']['SetTagPlaylist'](arg1, arg2);
}

export function SetTitleSeparator(arg1) {
  return window['go']['backend']['App']['SetTitleSeparator'](arg1);
}

export function SetTrayUploadProgress(arg1) {
  return window['go']['backend']['App']['SetTrayUploadProgress'](arg1);
}

export function SetVideoGames(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['SetVideoGames'](arg1, arg2, arg3, arg4, arg5);
}

export function SetVideosPlaylist(arg1, arg2, arg3) {
  return window['go']['backend']['App']['SetVideosPlaylist'](arg1, arg2, arg3);
}

export function SetWatchFolderEnabled(arg1) {
  return window['go']['backend']['App']['SetWatchFolderEnabled'](arg1);
}

export function ShowUploadNotification(arg1, arg2) {
  return window['go']['backend']['App']['ShowUploadNotification'](arg1, arg2);
}

export function StartYouTubeAuth() {
  return window['go']['backend']['App']['StartYouTubeAuth']();
}

export function Startup(arg1) {
  return window['go']['backend']['App']['Startup'](arg1);
}

export function SyncChannelData() {
  return window['go']['backend']['App']['SyncChannelData']();
}

export function SyncRecentVideos(arg1) {
  return window['go']['backend']['App']['SyncRecentVideos'](arg1);
}

export function SyncSteamData() {
  return window['go']['backend']['App']['SyncSteamData']();
}

export function UnlinkLocalVideo(arg1) {
  return window['go']['backend']['App']['UnlinkLocalVideo'](arg1);
}

export function UpdateYouTubeVideoMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateYouTubeVideoMetadata'](arg1, arg2, arg3, arg4);
}

export function UploadToYouTube(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['backend']['App']['UploadToYouTube'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
