// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function AddFolder():Promise<string>;

export function AddVideoToPlaylist(arg1:string,arg2:string):Promise<void>;

export function CancelUpload(arg1:string):Promise<void>;

export function CreatePlaylist(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteFiles(arg1:Array<string>):Promise<void>;

export function GetAPILogs(arg1:number):Promise<Array<backend.APILog>>;

export function GetAutoLaunch():Promise<boolean>;

export function GetCacheDir():Promise<string>;

export function GetChannelPlaylists(arg1:string):Promise<Array<backend.YTPlaylist>>;

export function GetChannelVideosPaginated(arg1:number,arg2:number,arg3:string,arg4:string):Promise<Record<string, any>>;

export function GetFolderSettings(arg1:string):Promise<backend.FolderConfig>;

export function GetOrCreatePlaylist(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPlaylistVideos(arg1:string):Promise<Array<backend.YTVideo>>;

export function GetQuotaUsedToday():Promise<number>;

export function GetStreamPort():Promise<number>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetThumbnail(arg1:string):Promise<string>;

export function GetVideoDuration(arg1:string):Promise<number>;

export function GetVideoPreview(arg1:string):Promise<string>;

export function GetVideos(arg1:string):Promise<Array<backend.VideoFile>>;

export function GetVideosFromFolders(arg1:Array<string>):Promise<Array<backend.VideoFile>>;

export function GetWatchFolderEnabled():Promise<boolean>;

export function GetYouTubeChannelInfo():Promise<backend.YouTubeChannel>;

export function ImportYouTubeJSON():Promise<void>;

export function IsYouTubeAuthed():Promise<boolean>;

export function LinkLocalToYouTube(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function LoadConfig():Promise<backend.Config>;

export function OpenFolderDialog():Promise<string>;

export function RegenerateThumbnail(arg1:string):Promise<string>;

export function RemoveFolder(arg1:string):Promise<void>;

export function SaveFolderSettings(arg1:string,arg2:backend.FolderConfig):Promise<void>;

export function SaveFolders(arg1:Array<string>):Promise<void>;

export function SaveVideoMetadata(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<void>;

export function SaveYouTubeCredentials(arg1:string,arg2:string):Promise<void>;

export function SetAutoLaunch(arg1:boolean):Promise<void>;

export function SetTrayUploadProgress(arg1:number):Promise<void>;

export function SetVideoGames(arg1:Array<string>,arg2:string):Promise<void>;

export function SetVideosPlaylist(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function SetWatchFolderEnabled(arg1:boolean):Promise<void>;

export function ShowUploadNotification(arg1:string,arg2:string):Promise<void>;

export function StartYouTubeAuth():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SyncChannelData():Promise<void>;

export function SyncRecentVideos(arg1:number):Promise<void>;

export function UnlinkLocalVideo(arg1:string):Promise<void>;

export function UpdateYouTubeVideoMetadata(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadToYouTube(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<void>;
