// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {backend} from '../models';
import {sql} from '../models';
import {context} from '../models';

export function AddFolder():Promise<string>;

export function AddVideoToPlaylist(arg1:string,arg2:string):Promise<void>;

export function CacheHandler():Promise<http.Handler>;

export function CancelUpload(arg1:string):Promise<void>;

export function CreatePlaylist(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DeleteFiles(arg1:Array<string>):Promise<void>;

export function DeleteGameProfile(arg1:string):Promise<void>;

export function DeletePlaylist(arg1:string):Promise<void>;

export function DisconnectSteam():Promise<void>;

export function GetAPILogs(arg1:number):Promise<Array<backend.APILog>>;

export function GetAutoLaunch():Promise<boolean>;

export function GetCacheDir():Promise<string>;

export function GetChannelAnalytics():Promise<backend.ChannelAnalytics>;

export function GetChannelPlaylists(arg1:string):Promise<Array<backend.YTPlaylist>>;

export function GetChannelVideosPaginated(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<Record<string, any>>;

export function GetDB():Promise<sql.DB>;

export function GetFolderSettings(arg1:string):Promise<backend.FolderConfig>;

export function GetOrCreatePlaylist(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetPlaylistVideos(arg1:string):Promise<Array<backend.YTVideo>>;

export function GetQuotaUsedToday():Promise<number>;

export function GetSteamAPIKey():Promise<string>;

export function GetSteamAppID(arg1:string):Promise<string>;

export function GetSteamDeveloperStats(arg1:string):Promise<Array<backend.SteamDevPubStats>>;

export function GetSteamGameAchievementPct(arg1:string):Promise<number>;

export function GetSteamGamesByDeveloper(arg1:string):Promise<Array<backend.SteamGameItem>>;

export function GetSteamGamesByPublisher(arg1:string):Promise<Array<backend.SteamGameItem>>;

export function GetSteamGamesByTag(arg1:string):Promise<Array<backend.SteamGameItem>>;

export function GetSteamID():Promise<string>;

export function GetSteamOverallStats():Promise<backend.SteamOverallStats>;

export function GetSteamPublisherStats(arg1:string):Promise<Array<backend.SteamDevPubStats>>;

export function GetSteamTagStats(arg1:string):Promise<Array<backend.SteamTagStats>>;

export function GetStreamPort():Promise<number>;

export function GetSyncStatus():Promise<Record<string, any>>;

export function GetThumbnail(arg1:string):Promise<string>;

export function GetVideoDuration(arg1:string):Promise<number>;

export function GetVideoPreview(arg1:string):Promise<string>;

export function GetVideos(arg1:string):Promise<Array<backend.VideoFile>>;

export function GetVideosFromFolders(arg1:Array<string>):Promise<Array<backend.VideoFile>>;

export function GetWatchFolderEnabled():Promise<boolean>;

export function GetYouTubeChannelInfo():Promise<backend.YouTubeChannel>;

export function ImportYouTubeJSON():Promise<void>;

export function InitTestDB(arg1:string):Promise<void>;

export function IsSteamSyncing():Promise<boolean>;

export function IsYouTubeAuthed():Promise<boolean>;

export function LinkLocalToYouTube(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function LoadConfig():Promise<backend.Config>;

export function LogFrontendEvent(arg1:string):Promise<void>;

export function LoginSteam():Promise<string>;

export function OpenFolderDialog():Promise<string>;

export function PurgePlaylistDuplicates(arg1:string):Promise<number>;

export function RegenerateThumbnail(arg1:string):Promise<string>;

export function RemoveFolder(arg1:string):Promise<void>;

export function SaveFolderSettings(arg1:string,arg2:backend.FolderConfig):Promise<void>;

export function SaveFolders(arg1:Array<string>):Promise<void>;

export function SaveGameProfile(arg1:string,arg2:backend.GameProfile):Promise<void>;

export function SaveRecentFieldValues(arg1:Record<string, Array<string>>):Promise<void>;

export function SaveSteamAPIKey(arg1:string):Promise<void>;

export function SaveVideoMetadata(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number,arg8:string,arg9:string,arg10:Record<string, string>):Promise<void>;

export function SaveYouTubeCredentials(arg1:string,arg2:string):Promise<void>;

export function SetAutoLaunch(arg1:boolean):Promise<void>;

export function SetTagPlaylist(arg1:string,arg2:string):Promise<void>;

export function SetTitleSeparator(arg1:string):Promise<void>;

export function SetTrayUploadProgress(arg1:number):Promise<void>;

export function SetVideoGames(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<void>;

export function SetVideosPlaylist(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function SetWatchFolderEnabled(arg1:boolean):Promise<void>;

export function ShowUploadNotification(arg1:string,arg2:string):Promise<void>;

export function StartYouTubeAuth():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function SyncChannelData():Promise<void>;

export function SyncRecentVideos(arg1:number):Promise<void>;

export function SyncSteamData():Promise<void>;

export function UnlinkLocalVideo(arg1:string):Promise<void>;

export function UpdatePlaylistVisibility(arg1:string,arg2:string):Promise<void>;

export function UpdatePlaylistsVisibility(arg1:Array<string>,arg2:string):Promise<number>;

export function UpdateYouTubeVideoMetadata(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UploadToYouTube(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:number):Promise<void>;
