// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetVideoPreview(arg1) {
  return window['go']['main']['App']['GetVideoPreview'](arg1);
}

export function GetVideos(arg1) {
  return window['go']['main']['App']['GetVideos'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
