// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetThumbnail(arg1:string):Promise<string>;

export function GetVideoPreview(arg1:string):Promise<string>;

export function GetVideos(arg1:string):Promise<Array<main.VideoFile>>;

export function Greet(arg1:string):Promise<string>;
