// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder() {
  return window['go']['main']['App']['AddFolder']();
}

export function GetCacheDir() {
  return window['go']['main']['App']['GetCacheDir']();
}

export function GetStreamPort() {
  return window['go']['main']['App']['GetStreamPort']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetVideoPreview(arg1) {
  return window['go']['main']['App']['GetVideoPreview'](arg1);
}

export function GetVideos(arg1) {
  return window['go']['main']['App']['GetVideos'](arg1);
}

export function GetVideosFromFolders(arg1) {
  return window['go']['main']['App']['GetVideosFromFolders'](arg1);
}

export function ImportYouTubeJSON() {
  return window['go']['main']['App']['ImportYouTubeJSON']();
}

export function IsYouTubeAuthed() {
  return window['go']['main']['App']['IsYouTubeAuthed']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function SaveFolders(arg1) {
  return window['go']['main']['App']['SaveFolders'](arg1);
}

export function SaveYouTubeCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveYouTubeCredentials'](arg1, arg2);
}

export function StartYouTubeAuth() {
  return window['go']['main']['App']['StartYouTubeAuth']();
}

export function UploadToYouTube(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UploadToYouTube'](arg1, arg2, arg3, arg4);
}
