// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder() {
  return window['go']['main']['App']['AddFolder']();
}

export function AddVideoToPlaylist(arg1, arg2) {
  return window['go']['main']['App']['AddVideoToPlaylist'](arg1, arg2);
}

export function CreatePlaylist(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreatePlaylist'](arg1, arg2, arg3);
}

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function GetAPILogs(arg1) {
  return window['go']['main']['App']['GetAPILogs'](arg1);
}

export function GetAutoLaunch() {
  return window['go']['main']['App']['GetAutoLaunch']();
}

export function GetCacheDir() {
  return window['go']['main']['App']['GetCacheDir']();
}

export function GetChannelPlaylists(arg1) {
  return window['go']['main']['App']['GetChannelPlaylists'](arg1);
}

export function GetChannelVideosPaginated(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetChannelVideosPaginated'](arg1, arg2, arg3, arg4);
}

export function GetFolderSettings(arg1) {
  return window['go']['main']['App']['GetFolderSettings'](arg1);
}

export function GetPlaylistVideos(arg1) {
  return window['go']['main']['App']['GetPlaylistVideos'](arg1);
}

export function GetQuotaUsedToday() {
  return window['go']['main']['App']['GetQuotaUsedToday']();
}

export function GetStreamPort() {
  return window['go']['main']['App']['GetStreamPort']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function GetThumbnail(arg1) {
  return window['go']['main']['App']['GetThumbnail'](arg1);
}

export function GetVideoDuration(arg1) {
  return window['go']['main']['App']['GetVideoDuration'](arg1);
}

export function GetVideoPreview(arg1) {
  return window['go']['main']['App']['GetVideoPreview'](arg1);
}

export function GetVideos(arg1) {
  return window['go']['main']['App']['GetVideos'](arg1);
}

export function GetVideosFromFolders(arg1) {
  return window['go']['main']['App']['GetVideosFromFolders'](arg1);
}

export function GetWatchFolderEnabled() {
  return window['go']['main']['App']['GetWatchFolderEnabled']();
}

export function GetYouTubeChannelInfo() {
  return window['go']['main']['App']['GetYouTubeChannelInfo']();
}

export function ImportYouTubeJSON() {
  return window['go']['main']['App']['ImportYouTubeJSON']();
}

export function IsYouTubeAuthed() {
  return window['go']['main']['App']['IsYouTubeAuthed']();
}

export function LinkLocalToYouTube(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LinkLocalToYouTube'](arg1, arg2, arg3, arg4);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function RegenerateThumbnail(arg1) {
  return window['go']['main']['App']['RegenerateThumbnail'](arg1);
}

export function RemoveFolder(arg1) {
  return window['go']['main']['App']['RemoveFolder'](arg1);
}

export function SaveFolderSettings(arg1, arg2) {
  return window['go']['main']['App']['SaveFolderSettings'](arg1, arg2);
}

export function SaveFolders(arg1) {
  return window['go']['main']['App']['SaveFolders'](arg1);
}

export function SaveVideoMetadata(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveVideoMetadata'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SaveYouTubeCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveYouTubeCredentials'](arg1, arg2);
}

export function SetAutoLaunch(arg1) {
  return window['go']['main']['App']['SetAutoLaunch'](arg1);
}

export function SetTrayUploadProgress(arg1) {
  return window['go']['main']['App']['SetTrayUploadProgress'](arg1);
}

export function SetVideoGames(arg1, arg2) {
  return window['go']['main']['App']['SetVideoGames'](arg1, arg2);
}

export function SetVideosPlaylist(arg1, arg2) {
  return window['go']['main']['App']['SetVideosPlaylist'](arg1, arg2);
}

export function SetWatchFolderEnabled(arg1) {
  return window['go']['main']['App']['SetWatchFolderEnabled'](arg1);
}

export function ShowUploadNotification(arg1, arg2) {
  return window['go']['main']['App']['ShowUploadNotification'](arg1, arg2);
}

export function StartYouTubeAuth() {
  return window['go']['main']['App']['StartYouTubeAuth']();
}

export function SyncChannelData() {
  return window['go']['main']['App']['SyncChannelData']();
}

export function UnlinkLocalVideo(arg1) {
  return window['go']['main']['App']['UnlinkLocalVideo'](arg1);
}

export function UpdateYouTubeVideoMetadata(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateYouTubeVideoMetadata'](arg1, arg2, arg3, arg4);
}

export function UploadToYouTube(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['UploadToYouTube'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
