// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddFolder():Promise<string>;

export function GetCacheDir():Promise<string>;

export function GetStreamPort():Promise<number>;

export function GetThumbnail(arg1:string):Promise<string>;

export function GetVideoPreview(arg1:string):Promise<string>;

export function GetVideos(arg1:string):Promise<Array<main.VideoFile>>;

export function GetVideosFromFolders(arg1:Array<string>):Promise<Array<main.VideoFile>>;

export function ImportYouTubeJSON():Promise<void>;

export function IsYouTubeAuthed():Promise<boolean>;

export function LoadConfig():Promise<main.Config>;

export function OpenFolderDialog():Promise<string>;

export function RemoveFolder(arg1:string):Promise<void>;

export function SaveFolders(arg1:Array<string>):Promise<void>;

export function SaveYouTubeCredentials(arg1:string,arg2:string):Promise<void>;

export function StartYouTubeAuth():Promise<void>;

export function UploadToYouTube(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;
